services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    # Usuwamy linię "user", aby kontener wystartował jako root i sam nadał sobie uprawnienia
    ports:
      - "8081:80"
    volumes:
      - /home/tomek/homelab-ops/filebrowser/data:/srv
      - /home/tomek/homelab-ops/filebrowser/config:/database
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
