- Infrastructure:
    - Portainer:
        icon: portainer.png
        href: https://192.168.1.53:9443
        server: my-docker
        container: portainer
        widget:
          type: portainer
          url: https://192.168.1.53:9443
          key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
          env: 3
          verify: false
    - AdGuard Home:
        icon: adguard-home.png
        href: http://192.168.1.53:8080
        server: my-docker
        container: adguard-home
        widget:
          type: adguard
          url: http://192.168.1.53:8080
          username: tomek
          password: "{{HOMEPAGE_VAR_ADGUARD_PASS}}"
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: http://192.168.1.53:81
        server: my-docker
        container: nginx-proxy-manager-app-1
        widget:
          type: npm
          url: http://192.168.1.53:81
          username: "{{HOMEPAGE_VAR_NPM_USER}}"
          password: "{{HOMEPAGE_VAR_NPM_PASS}}"

- Monitoring:
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://192.168.1.53:3001
        server: my-docker
        container: uptime-kuma
        widget:
          type: uptimekuma
          url: http://192.168.1.53:3001
          slug: default
    - Grafana:
        icon: grafana.png
        href: http://192.168.1.53:3002
        server: my-docker
        container: grafana
        widget:
          type: prometheus
          url: http://192.168.1.53:9090
          metric: grafana_stats_dashboards_total
          label: Dashboards
    - Prometheus:
        icon: prometheus.png
        href: http://192.168.1.53:9090
        server: my-docker
        container: prometheus
        widget:
          type: prometheus
          url: http://192.168.1.53:9090

- Security & Tools:
    - Vaultwarden:
        icon: vaultwarden.png
        href: http://192.168.1.53:8083
        server: my-docker
        container: vaultwarden
    - File Browser:
        icon: filebrowser.png
        href: http://192.168.1.53:8081
        server: my-docker
        container: filebrowser

- System Metrics:
    - Node Exporter:
        icon: prometheus.png
        server: my-docker
        container: node-exporter
        widget:
          type: prometheus
          url: http://192.168.1.53:9090
          metric: 
            - (1 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])))) * 100
            - (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100
          label: 
            - CPU (%)
            - RAM (%)
    - cAdvisor:
        icon: cadvisor.png
        server: my-docker
        container: cadvisor
