- Infrastructure:
    - Portainer:
        icon: portainer.png
        href: https://192.168.1.53:9443
        server: my-docker
        container: portainer
        health: https://192.168.1.53:9443
        widget:
          type: portainer
          url: https://192.168.1.53:9443
          key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
          env: 3
          verify: false
    - AdGuard Home:
        icon: adguard-home.png
        href: http://192.168.1.53:8080
        server: my-docker
        container: adguard-home
        # Kluczowe zmiany dla statusu:
        health: http://192.168.1.53:8080
        proxy: true
        showstats: true
        widget:
          type: adguard
          url: http://192.168.1.53:8080
          username: tomek
          password: "{{HOMEPAGE_VAR_ADGUARD_PASS}}"
          version: v1
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: http://192.168.1.53:81
        server: my-docker
        container: nginx-proxy-manager-app-1
        health: http://192.168.1.53:81
        widget:
          type: npm
          url: http://192.168.1.53:81
          username: "{{HOMEPAGE_VAR_NPM_USER}}"
          password: "{{HOMEPAGE_VAR_NPM_PASS}}"

- Monitoring:
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://192.168.1.53:3001
        server: my-docker
        container: uptime-kuma
        widget:
          type: uptimekuma
          url: http://192.168.1.53:3001
          monitors: true
          slug: default
    - Grafana:
        icon: grafana.png
        href: http://192.168.1.53:3002
        server: my-docker
        container: grafana
        widget:
          type: prometheus
          url: http://192.168.1.53:9090
          metric: grafana_stats_dashboards_total
          label: Dashboards
    - Prometheus:
        icon: prometheus.png
        href: http://192.168.1.53:9090
        server: my-docker
        container: prometheus
        widget:
          type: prometheus
          url: http://192.168.1.53:9090

- Security & Tools:
    - Vaultwarden:
        icon: vaultwarden.png
        href: http://192.168.1.53:8083
        server: my-docker
        container: vaultwarden
        health: http://192.168.1.53:8083
    - File Browser:
        icon: filebrowser.png
        href: http://192.168.1.53:8081
        server: my-docker
        container: filebrowser
        health: http://192.168.1.53:8081

- System Metrics:
    - CPU Usage:
        icon: glances.png
        widget:
          type: customapi
          url: http://192.168.1.53:61208/api/4/quicklook
          mappings:
            - field: cpu
              label: CPU
              format: percent
        server: my-docker
        container: glances
    - RAM Usage:
        icon: glances.png
        widget:
          type: customapi
          url: http://192.168.1.53:61208/api/4/quicklook
          mappings:
            - field: mem
              label: RAM
              format: percent
        server: my-docker
        container: glances
    - Disk Usage:
        icon: glances.png
        widget:
          type: customapi
          url: http://192.168.1.53:61208/api/4/fs
          mappings:
            - field: 0.percent
              label: DISK
              format: percent
        server: my-docker
        container: glances
    - Log Management:
        icon: grafana.png
        href: http://192.168.1.53:3002/explore
        description: Centralized Logs (Grafana)
        server: my-docker
        container: loki
    - cAdvisor:
        icon: cadvisor.png
        server: my-docker
        container: cadvisor
