- Infrastructure:
    - AdGuard Home:
        icon: adguard-home.png
        href: http://192.168.1.53:8080
        description: DNS Filter
        widget:
            type: adguard
            url: http://192.168.1.53:8080
            username: tomek
            password: {{HOMEPAGE_VAR_ADGUARD_PASS}}
    - Portainer:
        icon: portainer.png
        href: https://ubuntu-lab.tailc02cb2.ts.net/portainer
        description: Docker Management
        widget:
            type: docker
            url: /var/run/docker.sock
            container: portainer
- Monitoring:
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://192.168.1.53:3001
        widget:
            type: docker
            url: /var/run/docker.sock
            container: uptime-kuma
    - Grafana:
        icon: grafana.png
        href: http://grafana.lab:3002
        widget:
            type: docker
            url: /var/run/docker.sock
            container: grafana
    - Prometheus:
        icon: prometheus.png
        href: http://192.168.1.53:9090
        widget:
            type: docker
            url: /var/run/docker.sock
            container: prometheus
- Storage:
    - File Manager:
        icon: filebrowser.png
        href: http://files.lab
        description: Cloud File Access
        widget:
            type: docker
            url: /var/run/docker.sock
            container: filebrowser
- Security:
    - Vaultwarden:
        icon: vaultwarden.png
        href: http://192.168.1.53:8083
        description: Password Manager
